  - alias: Humidity_Setpoint
    trigger:
      platform: state
      entity_id: input_number.humidity_setpoint
    action:
      service: light.turn_on
      data_template:
        entity_id: light.boca_thermostat_1_3
        brightness_pct: "{{ trigger.to_state.state | int }}"

  - alias: Humidity_Setpoint_HA
    trigger:
      platform: state
      entity_id: light.boca_thermostat_1_3
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.humidity_setpoint
        value: "{{ states.light.boca_thermostat_1_3.attributes.V_PERCENTAGE | int }}"

  - alias: "Sunset"
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.livingroom_lamp

  - alias: "NightTime"
    trigger:
      platform: time
      at: '23:00:00'
    action:
      service: homeassistant.turn_off
      entity_id: switch.livingroom_lamp

  - alias: "Livingroom Humidity"
    trigger:
      platform: numeric_state
      entity_id: sensor.temperatureandhumidity_2_0
      above: 60.0
    action:
      service: notify.bocaha
      data:
        message: "Livingroom humidity above 60%"
        title: "Climate Alert"


  - alias: " Guest Bedroom Humidity"
    trigger:
      platform: numeric_state
      entity_id: sensor.temperatureandhumidity_5_0
      above: 60.0

    action:
      service: notify.bocaha
      data:
        message: "Guest bedroom humidity above 60%"
        title: "Climate Alert"


  - alias: "DHW Water Alert"
    trigger:
    - platform: state
      entity_id: binary_sensor.airconditioner_leak_7_2
      from: 'off'
      to: 'on'
    action:
    - service: notify.bocaha
      data:
        message: "DHW Water Leak at {{ states.sensor.airconditioner_leak_7_3.state }}"
        title: "Leak Alert"


  - alias: "AC Water Alert"
    trigger:
    - platform: state
      entity_id: binary_sensor.airconditioner_leak_7_0
      from: 'off'
      to: 'on'
    action:
    - service: notify.bocaha
      data:
        message: "AC Water Leak at {{ states.sensor.airconditioner_leak_7_1.state }}"
        title: "Leak Alert"
