#Sensors
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
#    - windSpeed
#    - pressure
#    - windDirection
    - humidity
#    - fog
    - cloudiness
#    - lowClouds
#    - mediumClouds
#    - highClouds
#    - dewpointTemperature

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: since_last_boot